---
title: "Robustly subtyping patients"
author: "Paul Agapow"
date: "`r Sys.Date()`"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{Robustly subtyping patients}
  %\VignetteEngine{knitr::rmarkdown}
  \usepackage[utf8]{inputenc}
  %\VignetteEncoding{UTF-8}
---

```{r setup, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```

## Background

Precision (or personalised or stratified medicine) means giving "the right
treatment for the right patient given at the right time". This in turn
requires that patients be *typed*: assigned to a class that goes beyond
clinical presentation (their appearance) and reflects the particular
mechanisms underlying their disease.

Typing is thus broadly a clustering and classification problem, but
identifying and validating these subtypes can be complex. There are many
possible methods that could be used. It is often unclear which work better.
In the absence of ground truths, it may be unclear if they work at all.
Where there are ground truths, typing may not reflect those truths.
Different methods may resolve patient clusters in different extents,
splitting or merging. Data preparation - cleaning or normalisation - may
be required. The newer multi-omic (integrated) methods may complicate these issues.


## Features

This package presents a number of tools and functions for improved and more
consistent subtyping, including:

* Unified and consistent interaces for subtyping practices
* Generation of synthetic data
* Validation via internal measures and external ground truths. 
* Functions for quality control and preprocessing of data
* Metrics and visualisations for assessing the results of subtyping
* Frameworks for exploration and tuning of various parameters
* Several well-understood datasets for testing and validating approaches
* Access to and uniform interfaces for several popular methods
* Functions for assessing robustness


## Conventions

We refer to a dataset that captures measurements for a set of patients as a
*sample-feature matrix*.

By convention, samples (patients) are the rows and features (measurements) the
columns of this table.

This package broadly follows the tidyverse style guide.


## Simple example

TODO


